// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLastProjectPath():Promise<string>;

export function OpenProject():Promise<main.ProjectData>;

export function ReopenLastProject():Promise<main.ProjectData>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveCsv(arg1:string):Promise<void>;
