// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRecentPaths() {
  return window['go']['main']['App']['CheckRecentPaths']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ConfirmClose(arg1) {
  return window['go']['main']['App']['ConfirmClose'](arg1);
}

export function DownloadAndInstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1, arg2);
}

export function GetCurrentOS() {
  return window['go']['main']['App']['GetCurrentOS']();
}

export function GetLastProjectPath() {
  return window['go']['main']['App']['GetLastProjectPath']();
}

export function GetQuests() {
  return window['go']['main']['App']['GetQuests']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function OpenProjectPath(arg1) {
  return window['go']['main']['App']['OpenProjectPath'](arg1);
}

export function RedefineRecentProject(arg1) {
  return window['go']['main']['App']['RedefineRecentProject'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function ReopenLastProject() {
  return window['go']['main']['App']['ReopenLastProject']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCsv(arg1) {
  return window['go']['main']['App']['SaveCsv'](arg1);
}
