// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function GetLastProjectPath() {
  return window['go']['main']['App']['GetLastProjectPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function ReopenLastProject() {
  return window['go']['main']['App']['ReopenLastProject']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCsv(arg1) {
  return window['go']['main']['App']['SaveCsv'](arg1);
}
