// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckRecentPaths():Promise<Array<string>>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ConfirmClose(arg1:boolean):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string):Promise<void>;

export function GetCurrentOS():Promise<string>;

export function GetLastProjectPath():Promise<string>;

export function GetQuests():Promise<main.QuestData>;

export function GetRecentProjects():Promise<Array<main.RecentProject>>;

export function GetVersion():Promise<string>;

export function OpenProject():Promise<main.ProjectData>;

export function OpenProjectPath(arg1:string):Promise<main.ProjectData>;

export function RedefineRecentProject(arg1:string):Promise<main.ProjectData>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function ReopenLastProject():Promise<main.ProjectData>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveCsv(arg1:string):Promise<void>;
